package aptracker.core;

import aptracker.core.Tracker.LocationState;
import aptracker.core.Tracker.Snapshot;
import aptracker.core.Tracker.Status;
import aptracker.core.data.GameData;
import aptracker.core.logic.CombatDifficulty;
import aptracker.core.logic.RequiredBosses;
import aptracker.core.logic.SlotOptions;
import com.google.gson.JsonParser;
import org.junit.jupiter.api.Test;

import java.util.List;
import java.util.Map;
import java.util.Set;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

class TrackerTest {

    private static final GameData DATA = GameData.load();

    // The shape of the JSON inside a real .apmc file generated by the 26.2 apworld.
    private static final String SLOT_DATA = """
            {"world_seed": 1, "seed_name": "1", "player_name": "Player", "player_id": 2, "client_version": 11,
             "structures": {"Overworld Structure 1": "Village", "Overworld Structure 2": "Nether Fortress",
                            "Nether Structure 1": "Pillager Outpost", "Nether Structure 2": "End City",
                            "The End Structure": "Bastion Remnant"},
             "advancement_goal": 45, "egg_shards_required": 0, "egg_shards_available": 0, "required_bosses": "both",
             "MC35": false, "death_link": true, "starting_items": "[]", "race": false, "immediate_respawn": true,
             "bosses_to_defeat": 3, "shuffle_structures": 1, "structure_compasses": 1, "combat_difficulty": 1,
             "include_hard_advancements": 1, "include_unreasonable_advancements": 0,
             "include_postgame_advancements": 0}
            """;

    private static SlotOptions slotOptions() {
        return SlotOptions.fromSlotData(JsonParser.parseString(SLOT_DATA).getAsJsonObject(), DATA);
    }

    private static LocationState find(Snapshot snapshot, String name) {
        return snapshot.locations().stream().filter(location -> location.name().equals(name)).findFirst().orElseThrow();
    }

    @Test
    void slotDataIsRead() {
        SlotOptions options = slotOptions();
        assertEquals(CombatDifficulty.NORMAL, options.combatDifficulty());
        assertTrue(options.structureCompasses());
        assertTrue(options.deathLink());
        assertTrue(options.includeHardAdvancements());
        assertFalse(options.includeUnreasonableAdvancements());
        assertFalse(options.includePostgameAdvancements());
        assertEquals(RequiredBosses.BOTH, options.requiredBosses());
        assertEquals(45, options.advancementGoal());
        assertEquals("Nether Fortress", options.structures().get("Overworld Structure 2"));
    }

    @Test
    void anEmptyInventoryOnlyReachesTheFreeOverworldAdvancements() {
        Snapshot snapshot = new Tracker(DATA, slotOptions()).evaluate(Map.of(), Set.of());

        assertEquals(DATA.locationNames().size(), snapshot.locations().size());
        assertEquals(Status.IN_LOGIC, find(snapshot, "Getting Wood").status());
        assertEquals(Status.IN_LOGIC, find(snapshot, "Stone Age").status());
        assertEquals(Status.OUT_OF_LOGIC, find(snapshot, "Hot Stuff").status());
        assertEquals(Status.OUT_OF_LOGIC, find(snapshot, "We Need to Go Deeper").status());
        for (LocationState location : snapshot.withStatus(Status.IN_LOGIC)) {
            assertEquals("Overworld", location.region(), location.name());
        }
        assertFalse(snapshot.enderDragonInLogic());
        assertFalse(snapshot.witherInLogic());
    }

    @Test
    void checkedLocationsAreReportedAsCheckedWhateverTheLogic() {
        long hotStuff = DATA.locationIds().get("Hot Stuff");
        Snapshot snapshot = new Tracker(DATA, slotOptions()).evaluate(Map.of(), Set.of(hotStuff));

        assertEquals(Status.CHECKED, find(snapshot, "Hot Stuff").status());
        assertEquals(1, snapshot.count(Status.CHECKED));
    }

    @Test
    void missingItemsAreListedWithTheTotalCopiesNeeded() {
        Tracker tracker = new Tracker(DATA, slotOptions());

        LocationState hotStuff = find(tracker.evaluate(Map.of("Progressive Tools", 1), Set.of()), "Hot Stuff");
        assertEquals(Map.of("Bucket", 1, "Progressive Resource Crafting", 1), hotStuff.missing());

        LocationState diamonds = find(tracker.evaluate(Map.of("Progressive Tools", 1), Set.of()), "Diamonds!");
        assertEquals(Map.of("Progressive Tools", 2, "Progressive Resource Crafting", 1), diamonds.missing());
    }

    @Test
    void missingItemsFollowTheCheapestAlternative() {
        Tracker tracker = new Tracker(DATA, slotOptions());
        Map<String, Integer> items = Map.of("Flint and Steel", 1, "Progressive Resource Crafting", 1, "Progressive Tools", 1);

        // The Nether Portal needs a Bucket or three Progressive Tools: the Bucket is one item away.
        LocationState nether = find(tracker.evaluate(items, Set.of()), "We Need to Go Deeper");
        assertEquals(Status.OUT_OF_LOGIC, nether.status());
        assertEquals(Map.of("Bucket", 1), nether.missing());
    }

    @Test
    void deathLinkRequiresABedToAdventure() {
        Map<String, Integer> items = Map.of("Progressive Weapons", 1, "Campfire", 1,
                "Structure Compass (Village)", 1);
        SlotOptions withDeathLink = slotOptions();
        SlotOptions withoutDeathLink = SlotOptions.builder(DATA)
                .structures(withDeathLink.structures())
                .build();

        assertEquals(Status.OUT_OF_LOGIC, find(new Tracker(DATA, withDeathLink).evaluate(items, Set.of()), "What a Deal!").status());
        assertEquals(Status.IN_LOGIC, find(new Tracker(DATA, withoutDeathLink).evaluate(items, Set.of()), "What a Deal!").status());
    }

    @Test
    void structureCompassesFollowTheShuffledStructures() {
        // The fortress is attached to "Overworld Structure 2": its compass opens it without the Nether.
        Map<String, Integer> items = Map.of("Progressive Weapons", 1, "Campfire", 1, "Bed", 1,
                "Structure Compass (Nether Fortress)", 1);
        Snapshot snapshot = new Tracker(DATA, slotOptions()).evaluate(items, Set.of());

        assertEquals(Status.IN_LOGIC, find(snapshot, "A Terrible Fortress").status());
        assertEquals(Status.OUT_OF_LOGIC, find(snapshot, "What a Deal!").status());
        assertEquals(Map.of("Structure Compass (Village)", 1), find(snapshot, "What a Deal!").missing());
    }

    @Test
    void excludedLocationsFollowTheOptions() {
        Snapshot snapshot = new Tracker(DATA, slotOptions()).evaluate(Map.of(), Set.of());

        // Hard advancements are included in this slot; unreasonable and postgame ones are not.
        assertFalse(find(snapshot, "Two by Two").excluded());
        assertTrue(find(snapshot, "Adventuring Time").excluded());
        assertTrue(find(snapshot, "Free the End").excluded());
        assertTrue(find(snapshot, "Withering Heights").excluded());
        assertFalse(find(snapshot, "Getting Wood").excluded());
    }

    @Test
    void receivedItemIdsAreCountedByName() {
        Tracker tracker = new Tracker(DATA, slotOptions());
        long tools = DATA.itemIds().get("Progressive Tools");
        long bucket = DATA.itemIds().get("Bucket");

        assertEquals(Map.of("Progressive Tools", 2, "Bucket", 1), tracker.countItems(List.of(tools, bucket, tools, 9999L)));
    }

    @Test
    void aFortressInTheEndIsRejected() {
        SlotOptions options = SlotOptions.builder(DATA)
                .structures(Map.of(
                        "Overworld Structure 1", "Village",
                        "Overworld Structure 2", "Pillager Outpost",
                        "Nether Structure 1", "End City",
                        "Nether Structure 2", "Bastion Remnant",
                        "The End Structure", "Nether Fortress"))
                .build();

        assertThrows(IllegalArgumentException.class, () -> new Tracker(DATA, options));
    }
}
